// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protos/v1/recording/recording.proto

package deliverble_recording_microservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadRecordingRequest wrapped with byte data
type UploadRecordingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recording []byte `protobuf:"bytes,1,opt,name=recording,proto3" json:"recording,omitempty"`
}

func (x *UploadRecordingRequest) Reset() {
	*x = UploadRecordingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_recording_recording_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRecordingRequest) ProtoMessage() {}

func (x *UploadRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_recording_recording_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRecordingRequest.ProtoReflect.Descriptor instead.
func (*UploadRecordingRequest) Descriptor() ([]byte, []int) {
	return file_protos_v1_recording_recording_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRecordingRequest) GetRecording() []byte {
	if x != nil {
		return x.Recording
	}
	return nil
}

type UploadRecordingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UploadRecordingResponse) Reset() {
	*x = UploadRecordingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_recording_recording_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRecordingResponse) ProtoMessage() {}

func (x *UploadRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_recording_recording_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRecordingResponse.ProtoReflect.Descriptor instead.
func (*UploadRecordingResponse) Descriptor() ([]byte, []int) {
	return file_protos_v1_recording_recording_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRecordingResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *UploadRecordingResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadRecordingResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_protos_v1_recording_recording_proto protoreflect.FileDescriptor

var file_protos_v1_recording_recording_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x36, 0x0a, 0x16, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x55, 0x0a,
	0x17, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x32, 0xde, 0x01, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x64, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a,
	0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x56, 0x32, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x42, 0x6c, 0x65, 0x2f, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x62, 0x6c, 0x65, 0x2d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_v1_recording_recording_proto_rawDescOnce sync.Once
	file_protos_v1_recording_recording_proto_rawDescData = file_protos_v1_recording_recording_proto_rawDesc
)

func file_protos_v1_recording_recording_proto_rawDescGZIP() []byte {
	file_protos_v1_recording_recording_proto_rawDescOnce.Do(func() {
		file_protos_v1_recording_recording_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_recording_recording_proto_rawDescData)
	})
	return file_protos_v1_recording_recording_proto_rawDescData
}

var file_protos_v1_recording_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_v1_recording_recording_proto_goTypes = []interface{}{
	(*UploadRecordingRequest)(nil),  // 0: prod.recording.UploadRecordingRequest
	(*UploadRecordingResponse)(nil), // 1: prod.recording.UploadRecordingResponse
}
var file_protos_v1_recording_recording_proto_depIdxs = []int32{
	0, // 0: prod.recording.recording_task.UploadRecording:input_type -> prod.recording.UploadRecordingRequest
	0, // 1: prod.recording.recording_task.UploadRecordingV2:input_type -> prod.recording.UploadRecordingRequest
	1, // 2: prod.recording.recording_task.UploadRecording:output_type -> prod.recording.UploadRecordingResponse
	1, // 3: prod.recording.recording_task.UploadRecordingV2:output_type -> prod.recording.UploadRecordingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_v1_recording_recording_proto_init() }
func file_protos_v1_recording_recording_proto_init() {
	if File_protos_v1_recording_recording_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_recording_recording_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRecordingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_recording_recording_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRecordingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_recording_recording_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v1_recording_recording_proto_goTypes,
		DependencyIndexes: file_protos_v1_recording_recording_proto_depIdxs,
		MessageInfos:      file_protos_v1_recording_recording_proto_msgTypes,
	}.Build()
	File_protos_v1_recording_recording_proto = out.File
	file_protos_v1_recording_recording_proto_rawDesc = nil
	file_protos_v1_recording_recording_proto_goTypes = nil
	file_protos_v1_recording_recording_proto_depIdxs = nil
}
